from backend.routes.storage_tsdb import tsdb_bp  # noqa: F401
from backend.routes.storage_rdbms import rdbms_bp  # noqa: F401
from backend.routes.storage_file import file_bp  # noqa: F401
from backend.routes.collector_mqtt import mqtt_bp  # noqa: F401
from backend.routes.collector_db import db_bp  # noqa: F401
from backend.routes.collector_file_watch import file_watch_bp  # noqa: F401
from backend.routes.collector_opcua import opcua_bp  # noqa: F401
from backend.routes.collector_modbus import modbus_bp  # noqa: F401
from backend.routes.collector_api import api_bp  # noqa: F401
from backend.routes.storage_retention import retention_bp  # noqa: F401
from backend.routes.pipeline import pipeline_bp  # noqa: F401
from backend.routes.metadata import metadata_bp  # noqa: F401
from backend.routes.catalog import catalog_bp  # noqa: F401
from backend.routes.engine_status import engine_status_bp  # noqa: F401
from backend.routes.engine_batch import engine_batch_bp  # noqa: F401
from backend.routes.engine_buffer import engine_buffer_bp  # noqa: F401
from backend.routes.engine_performance import engine_perf_bp  # noqa: F401
from backend.routes.integration import integration_bp  # noqa: F401
from backend.routes.monitoring import monitoring_bp  # noqa: F401
from backend.routes.alarm import alarm_bp  # noqa: F401
from backend.routes.admin import admin_bp  # noqa: F401
from backend.routes.backup import backup_bp  # noqa: F401
from backend.routes.gateway import gateway_bp  # noqa: F401
from backend.routes.collector_import import import_bp  # noqa: F401
